# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

os:
  - linux

dist:
  - xenial

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - libhdf5-dev
      - python3.6

cache:
  - packages
  - apt
  - directories:
    - $HOME/.cache/pip

before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.6 get-pip.py
  - mkdir -p ~/bin && export PATH=~/bin/:$PATH
  - ln -s $(which python3.6) ~/bin/python
  - ln -s $(which pip3.6) ~/bin/pip
  - sudo pip install --upgrade pip
  - pip install --user -q phate

install:
  - cd python; pip install --user -q .
  - cd ../Rmagic; R -e 'install.packages("devtools", repos="http://cloud.r-project.org")'
  - R -e 'devtools::install_deps(dep = T, upgrade="always")'
  - cd ..

script:
  - cd Rmagic; R CMD build .
  - R CMD check *tar.gz
  - cd ../python; pip install --user -q .[test]
  - python setup.py test
  - pip install --user -q .[doc]
  - cd doc; make html
  - cd ..

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master

warnings_are_errors: true
