# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

os:
  - linux

dist:
  - xenial

r:
  - release
  - devel

cache:
  - packages
  - apt
  - directories:
    - $HOME/.cache/pip

before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3 get-pip.py
  - sudo pip3 install --upgrade pip
  - pip3 install --user -q phate

install:
  - cd python; pip3 install --user -q .; cd ..
  - cd Rmagic; R -e 'install.packages("devtools", repos="http://cloud.r-project.org")'
  - R -e "devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0')"
  - R -e 'devtools::install_deps(dep = T)'; cd ..

script:
  - cd Rmagic; R CMD build .
  - R CMD check *tar.gz
  - cd ../python; pip3 install --user -q .[test,doc]
  - python3 setup.py test
  - cd doc; make html; cd ..

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master

warnings_are_errors: true
